#!/usr/bin/env python3
"""
tests/skill-refs/check-skill-refs.py

Scans the PACKAGED skill (`dist/agent-redline/`) for path references inside
markdown files and template files, and verifies every reference either:

  (a) resolves to a file that ships in the package, OR
  (b) appears in CONSUMING_REPO_PATHS — paths the agent is documented to
      produce in the consuming repo during bootstrap, OR
  (c) appears in SEARCH_PATTERNS — paths that are search globs the agent
      uses to detect existing repo state, not paths that need to exist.

The test catches the class of bug that bit Pallium's bootstrap: skill
content referencing a `scripts/agent-redline-report.sh` that doesn't
exist, or telling the agent to invoke a reporter the bootstrap never
vendored.

Why scan dist/, not source: package-skill.sh applies path substitutions
(core/reporter/reporter.py -> scripts/agent-redline-report.py, etc.).
The agent reads the SUBSTITUTED text, so that's what we validate.

Exit codes:
  0 — every reference resolves
  1 — script error
  2 — at least one dangling reference
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DIST = REPO_ROOT / "dist" / "agent-redline"

# Paths the bootstrap-mode skill is documented to produce in the
# CONSUMING repo (not in the skill itself). When skill content
# references these, they're instructions, not file dependencies.
#
# To add a new "consuming-repo path", check that bootstrap-mode.md or an
# extension's scaffold.md actually instructs the agent to create it.
CONSUMING_REPO_PATHS = {
    # Bootstrap creates this from core/templates/pre-push-check.sh
    "scripts/agent-redline-check.sh",
    # Bootstrap vendors core/reporter/reporter.py (shipped as
    # scripts/agent-redline-report.py inside the skill) into the consuming repo
    "scripts/agent-redline-report.py",
    # Python extension's scaffold vendors this from
    # extensions/python/scripts/run-import-linter.py
    "scripts/run-import-linter.py",
    # Bootstrap writes this from extension defaults
    "agent-redline-policy.yaml",
    # Per-checkpoint docs land in the consuming repo's docs/agent/
    "docs/agent/",
    # PR template
    ".github/pull_request_template.md",
    # CI proposal (not committed; written as a file the developer reviews)
    "docs/agent-redline-ci-proposal.md",
    # Build artifacts a CI workflow produces
    "build/import-linter-report.json",
    "build/changed-files.txt",
    "build/verdict.json",
    "build/comment.md",
    # The architecture-test glob bootstrap fills in for Spring repos
    "build/test-results/",
}

# Glob/wildcard patterns the agent uses to FIND existing files in the
# consuming repo. Not real file references.
SEARCH_PATTERNS = {
    "scripts/pre-push",
    "scripts/pre-push*",
    ".git/hooks/pre-push",
}

# Paths that live in the agent-redline SOURCE repo (not the package, not
# the consuming repo). Mentioned in the package's README as part of the
# "this is generated by..." narrative. Not file dependencies the agent
# acts on.
SOURCE_REPO_PATHS = {
    "scripts/package-skill.sh",
}

# Regex catching path references we care about. Three families:
#   scripts/<name>      — bash/python scripts the agent runs or vendors
#   assets/<path>       — anything under the packaged skill's assets/
#   references/<path>   — anything under references/per-checkpoint/
PATH_REF_RE = re.compile(
    r"(?<![/\w])"                       # left boundary: no preceding slash or word char
    r"((?:scripts|assets|references)/"  # the three families
    r"[A-Za-z0-9_./-]+)"                # the rest of the path
    r"(?![/\w])"                        # right boundary
)


def collect_references(text: str) -> set[str]:
    """Pull every scripts/*, assets/*, references/* reference from text.

    Strips trailing punctuation (`.`/`,`/`)`/`:`/etc.) and drops backtick
    fences. Returns unique paths."""
    refs: set[str] = set()
    for m in PATH_REF_RE.finditer(text):
        ref = m.group(1).rstrip(".,:;)`'\"")
        if ref:
            refs.add(ref)
    return refs


def file_ships_in_skill(ref: str) -> bool:
    """Does this path resolve to a real file in dist/agent-redline/?"""
    full = DIST / ref
    if full.is_file() or full.is_dir():
        return True
    # Glob support — `scripts/pre-push*` would match here if such a file existed.
    if any(c in ref for c in "*?["):
        return any(DIST.glob(ref))
    return False


def is_consuming_repo_path(ref: str) -> bool:
    """Does the reference target a path bootstrap creates IN THE CONSUMING REPO?

    Match either an exact entry or a directory-prefix entry (entries
    ending in `/`)."""
    if ref in CONSUMING_REPO_PATHS:
        return True
    # Directory-prefix match
    for known in CONSUMING_REPO_PATHS:
        if known.endswith("/") and ref.startswith(known):
            return True
    return False


def is_search_pattern(ref: str) -> bool:
    return ref in SEARCH_PATTERNS


def main() -> int:
    if not DIST.exists():
        print(f"error: package not built at {DIST}. Run scripts/package-skill.sh first.", file=sys.stderr)
        return 1

    # Files in dist/ to scan: every markdown + template the agent reads.
    targets: list[Path] = []
    for pattern in ("*.md", "**/*.md", "**/*.template"):
        targets.extend(p for p in DIST.glob(pattern) if p.is_file())
    targets = sorted(set(targets))

    # Also scan the pre-push template — agent doesn't read it directly,
    # but bootstrap copies it verbatim, so its path references end up in
    # the consuming repo.
    template_dir = DIST / "assets" / "templates"
    if template_dir.exists():
        for p in template_dir.glob("*.sh"):
            targets.append(p)

    failures: list[str] = []
    refs_checked = 0
    files_seen = 0

    for path in targets:
        text = path.read_text(encoding="utf-8")
        rel = path.relative_to(DIST)
        files_seen += 1
        for ref in sorted(collect_references(text)):
            refs_checked += 1
            if file_ships_in_skill(ref):
                continue
            if is_consuming_repo_path(ref):
                continue
            if is_search_pattern(ref):
                continue
            if ref in SOURCE_REPO_PATHS:
                continue
            failures.append(f"{rel}: dangling reference '{ref}'")

    print()
    print(f"scanned {files_seen} file(s) in dist/agent-redline/; checked {refs_checked} path reference(s).")
    if failures:
        for f in failures:
            print(f"FAIL  {f}", file=sys.stderr)
        print(f"\n{len(failures)} dangling reference(s).", file=sys.stderr)
        return 2
    print("all skill path references resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
