#!/usr/bin/env bash
# scripts/build-vendored-checker.sh
#
# Build a self-contained agent-workflow-check.py from the core/checker/
# package + the small slice of core/work_record/ and core/config/ it
# depends on.
#
# The vendored output is what consuming repos install at
# scripts/agent-workflow-check.py — see the demo repo's main branch.
# We rebuild it from source on every slice bump so the demo repo and
# the dev repo do not drift.
#
# Usage:
#   scripts/build-vendored-checker.sh                  # write to stdout
#   scripts/build-vendored-checker.sh <output-path>    # write to file

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="${1:-/dev/stdout}"

if command -v python >/dev/null 2>&1; then
  PY=python
elif command -v python3 >/dev/null 2>&1; then
  PY=python3
else
  echo "error: no python interpreter found on PATH" >&2
  exit 1
fi

"$PY" - "$REPO_ROOT" "$OUTPUT" <<'PYEOF'
"""Concatenate the dev-repo source files the checker needs into one script.

The result is a single Python file the consuming repo drops at
scripts/agent-workflow-check.py. It depends only on PyYAML and
jsonschema, which the GitHub Action installs explicitly.

Strategy: take the bodies of each source file, strip their
``from core.X import ...`` lines (the symbols are present in this
flat script), prepend a banner, append a CLI dispatcher, and inline
the schema so the vendored script does not need to find files outside
itself.
"""

from __future__ import annotations

import pprint as _pprint_for_inlining
import json as _json_for_inlining
import re
import sys
from pathlib import Path

REPO_ROOT = Path(sys.argv[1]).resolve()
OUTPUT = Path(sys.argv[2]) if sys.argv[2] != "/dev/stdout" else None

# Order matters: each file may only reference symbols defined above it.
SOURCES = [
    "core/work_record/parser.py",
    "core/work_record/backend.py",
    "core/work_record/local_backend.py",
    "core/config/loader.py",
    "core/checker/verdict.py",
    "core/checker/redline_verdict.py",
    "core/checker/predicates.py",
    "core/checker/checker.py",
]

SCHEMA_SOURCE = "core/schema/agent-workflow.schema.json"

# Read the schema once and embed it as a Python literal so the vendored
# script does not need to find a file outside itself. The replacement
# also drops the loader's ``_schema()`` helper since it's no longer
# needed.
_schema_text = _pprint_for_inlining.pformat(
    _json_for_inlining.loads((REPO_ROOT / SCHEMA_SOURCE).read_text(encoding="utf-8")),
    indent=2,
    width=100,
    sort_dicts=False,
)

BANNER = f'''\
#!/usr/bin/env python3
"""agent-workflow CI checker (vendored).

Generated from https://github.com/rore/agent-workflow by
``scripts/build-vendored-checker.sh``. Do not edit this file in the
consuming repo — re-run the build script from the dev repo and replace
this file when the checker changes.

Dependencies: PyYAML, jsonschema. The Action installs them explicitly;
the consuming repo does not need to vendor them.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Literal, Protocol, TypedDict, runtime_checkable

import jsonschema
import yaml

# Inlined from core/schema/agent-workflow.schema.json at build time.
_INLINED_SCHEMA = {_schema_text}

'''


def strip_local_imports(text: str) -> str:
    """Remove ``from core.*`` / ``from .*`` import statements from the source.

    Handles both single-line and parenthesised multi-line forms. The
    vendored script has every symbol in one namespace, so the
    cross-package imports are dead weight (and wrong — ``from core.X``
    fails at runtime when the script is invoked as a standalone file).

    For ``import X as Y`` aliases on local sources, rewrite the alias
    everywhere in the file so the body still resolves after flattening.
    Only ``from core.X import Y as Z`` is supported here — that's the
    only aliased local import in the slice today.
    """
    # First pass: collect alias rewrites and decide which lines to drop.
    alias_re = re.compile(
        r"^\s*from (?:core\.|\.)[\w.]+\s+import\s+([\w]+)\s+as\s+([\w]+)\s*$"
    )
    aliases: dict[str, str] = {}
    lines = text.splitlines(keepends=True)
    out_lines: list[str] = []
    skip_until_close_paren = False
    for line in lines:
        if skip_until_close_paren:
            if ")" in line:
                skip_until_close_paren = False
            continue
        m = alias_re.match(line.rstrip("\n"))
        if m:
            real_name, alias_name = m.group(1), m.group(2)
            aliases[alias_name] = real_name
            continue
        stripped = line.lstrip()
        if stripped.startswith("from core.") or stripped.startswith("from ."):
            if "(" in line and ")" not in line:
                skip_until_close_paren = True
            continue
        out_lines.append(line)
    body = "".join(out_lines)
    # Second pass: rewrite alias usages back to the real name.
    for alias_name, real_name in aliases.items():
        body = re.sub(rf"\b{re.escape(alias_name)}\b", real_name, body)
    return body


def strip_future_and_stdlib_imports(text: str) -> str:
    """Drop ``from __future__`` and top-level stdlib imports the banner already provides."""
    redundant_re = re.compile(
        r"^(?:from __future__ import annotations"
        r"|import argparse"
        r"|import json"
        r"|import re"
        r"|import sys"
        r"|from dataclasses import [^\n]*"
        r"|from pathlib import Path"
        r"|from typing import [^\n]*"
        r"|import yaml"
        r"|import jsonschema)\s*$"
    )
    out_lines: list[str] = []
    for line in text.splitlines():
        if redundant_re.match(line):
            continue
        out_lines.append(line)
    # Strip a trailing module-only ``if __name__ == "__main__"`` block —
    # the vendored script has its own dispatcher.
    text = "\n".join(out_lines)
    text = re.sub(
        r'\n+if __name__ == "__main__":.*$',
        "",
        text,
        flags=re.DOTALL,
    )
    return text


def patch_schema_loader(text: str) -> str:
    """Replace loader.py's _schema() with a version that returns the inlined dict.

    The dev-side ``_schema()`` reads ``core/schema/agent-workflow.schema.json``
    from a path relative to ``loader.py``. The vendored script lives in
    a different directory in the consuming repo, so the path is wrong
    and the schema file isn't shipped to consumers anyway. Replace the
    helper plus its path constants with a tiny in-memory accessor.
    """
    # Drop the path constants. They reference ``__file__`` which is
    # this script in the consuming repo and would resolve to garbage.
    text = re.sub(
        r"\n_REPO_ROOT = [^\n]+\n_SCHEMA_PATH = [^\n]+\n",
        "\n",
        text,
    )
    # Replace the docstring + body of _schema() with the inlined dict.
    text = re.sub(
        r"def _schema\(\) -> dict\[str, Any\]:.*?return json\.loads\([^\n]+\)\n",
        "def _schema() -> dict[str, Any]:\n    \"\"\"Return the inlined config schema.\"\"\"\n    return _INLINED_SCHEMA\n",
        text,
        count=1,
        flags=re.DOTALL,
    )
    return text


def main_entry() -> str:
    """Tail block that wires the CLI."""
    return '''

if __name__ == "__main__":
    sys.exit(main())
'''


repo_root = REPO_ROOT
chunks: list[str] = [BANNER]

for src in SOURCES:
    path = repo_root / src
    body = path.read_text(encoding="utf-8")
    body = strip_local_imports(body)
    body = strip_future_and_stdlib_imports(body)
    if src.endswith("loader.py"):
        body = patch_schema_loader(body)
    chunks.append(f"# ----- {src} -----\n\n")
    chunks.append(body.rstrip() + "\n\n")

chunks.append(main_entry())
output = "".join(chunks)

if OUTPUT is None:
    sys.stdout.write(output)
else:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}", file=sys.stderr)
PYEOF
